### ISSUE TITLE
[Bug] 启动时插件报错，并无法连接至WebSocket

### ISSUE THREAD

**Issue by GLDYM** [IllTamer/infinitebot4#14]
由3.1.7更新至3.2.0后，启动服务器时插件报错，启动后反复提示“检测到 WebSocket 连接断开，尝试重连 go-cqhttp 中”。
[Error1.txt](https://github.com/IllTamer/infinitebot3/files/11954413/Error1.txt)

删除配置文件后重启，报了另外一个错误，同样连接不上WebSocket。
[Error2.txt](https://github.com/IllTamer/infinitebot3/files/11954421/Error2.txt)

回退至3.1.7后恢复正常。

**Comment by IllTamer** [comment]
infinitebot4已更新
